### ISSUE TITLE
Add Elm Test + CI 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/phoenix-elm-starter#2]
There is a glaring gap in this "starter": **`Elm Test`**!

# Todo

+ [ ] Add `Elm Test` to [`/assets/elm`](https://github.com/dwyl/phoenix-elm-starter/tree/main/assets/elm)
  see: https://package.elm-lang.org/packages/elm-explorations/test/latest/
+ [ ] Create a "hello world" test.
+ [ ] Figure out how to run the `Elm` tests  on GitHub Actions/Workflows CI.
+ [ ] Document all the steps so that we can replicate this in a "real" project. 

@SimonLab as discussed, if you have time, please add this. Thanks!

**Comment by nelsonic** [comment]
Potentially useful: https://github.com/mpizenberg/elm-tooling-action
